// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity_logs.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActivitiesByUser = `-- name: CountActivitiesByUser :one
SELECT COUNT(*) FROM activity_logs WHERE user_id = $1
`

func (q *Queries) CountActivitiesByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActivitiesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertActivityLog = `-- name: InsertActivityLog :exec
INSERT INTO activity_logs (
    request_id, user_id, chat_id, username, activity_type, command,
    message_id, message_thread_id, success, error_message, metadata, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12
)
`

type InsertActivityLogParams struct {
	RequestID       *string            `json:"request_id"`
	UserID          int64              `json:"user_id"`
	ChatID          int64              `json:"chat_id"`
	Username        *string            `json:"username"`
	ActivityType    string             `json:"activity_type"`
	Command         *string            `json:"command"`
	MessageID       *int64             `json:"message_id"`
	MessageThreadID *int64             `json:"message_thread_id"`
	Success         bool               `json:"success"`
	ErrorMessage    *string            `json:"error_message"`
	Metadata        json.RawMessage    `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertActivityLog(ctx context.Context, arg InsertActivityLogParams) error {
	_, err := q.db.Exec(ctx, insertActivityLog,
		arg.RequestID,
		arg.UserID,
		arg.ChatID,
		arg.Username,
		arg.ActivityType,
		arg.Command,
		arg.MessageID,
		arg.MessageThreadID,
		arg.Success,
		arg.ErrorMessage,
		arg.Metadata,
		arg.CreatedAt,
	)
	return err
}
