// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertChat = `-- name: UpsertChat :one
INSERT INTO chats (chat_id, title, type, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (chat_id) DO UPDATE SET
    title      = EXCLUDED.title,
    type       = EXCLUDED.type,
    updated_at = EXCLUDED.updated_at
RETURNING id, chat_id, title, type, created_at, updated_at
`

type UpsertChatParams struct {
	ChatID    int64              `json:"chat_id"`
	Title     *string            `json:"title"`
	Type      *string            `json:"type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertChat(ctx context.Context, arg UpsertChatParams) (Chats, error) {
	row := q.db.QueryRow(ctx, upsertChat,
		arg.ChatID,
		arg.Title,
		arg.Type,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Chats
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Title,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
