// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: command_logs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertCommandLog = `-- name: InsertCommandLog :exec
INSERT INTO command_logs (
    user_id, chat_id, username, command, full_command,
    message_id, message_thread_id,
    execution_time, success, error_message, response_length, created_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7,
    $8, $9, $10, $11, $12
)
`

type InsertCommandLogParams struct {
	UserID          int64              `json:"user_id"`
	ChatID          int64              `json:"chat_id"`
	Username        *string            `json:"username"`
	Command         string             `json:"command"`
	FullCommand     *string            `json:"full_command"`
	MessageID       *int64             `json:"message_id"`
	MessageThreadID *int64             `json:"message_thread_id"`
	ExecutionTime   *int64             `json:"execution_time"`
	Success         bool               `json:"success"`
	ErrorMessage    *string            `json:"error_message"`
	ResponseLength  *int64             `json:"response_length"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertCommandLog(ctx context.Context, arg InsertCommandLogParams) error {
	_, err := q.db.Exec(ctx, insertCommandLog,
		arg.UserID,
		arg.ChatID,
		arg.Username,
		arg.Command,
		arg.FullCommand,
		arg.MessageID,
		arg.MessageThreadID,
		arg.ExecutionTime,
		arg.Success,
		arg.ErrorMessage,
		arg.ResponseLength,
		arg.CreatedAt,
	)
	return err
}
