// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: download_activities.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDownloadsByUser = `-- name: CountDownloadsByUser :one
SELECT COUNT(*) FROM download_activities WHERE user_id = $1 AND action = 'unrestrict'
`

func (q *Queries) CountDownloadsByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countDownloadsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertDownloadActivity = `-- name: InsertDownloadActivity :exec
INSERT INTO download_activities (
    request_id, user_id, chat_id, download_id, original_link, file_name,
    file_size, host, action, success, error_message, metadata, created_at,
    torrent_activity_id
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12, $13,
    $14
)
`

type InsertDownloadActivityParams struct {
	RequestID         *string            `json:"request_id"`
	UserID            int64              `json:"user_id"`
	ChatID            int64              `json:"chat_id"`
	DownloadID        *string            `json:"download_id"`
	OriginalLink      *string            `json:"original_link"`
	FileName          *string            `json:"file_name"`
	FileSize          *int64             `json:"file_size"`
	Host              *string            `json:"host"`
	Action            string             `json:"action"`
	Success           bool               `json:"success"`
	ErrorMessage      *string            `json:"error_message"`
	Metadata          json.RawMessage    `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	TorrentActivityID *int64             `json:"torrent_activity_id"`
}

func (q *Queries) InsertDownloadActivity(ctx context.Context, arg InsertDownloadActivityParams) error {
	_, err := q.db.Exec(ctx, insertDownloadActivity,
		arg.RequestID,
		arg.UserID,
		arg.ChatID,
		arg.DownloadID,
		arg.OriginalLink,
		arg.FileName,
		arg.FileSize,
		arg.Host,
		arg.Action,
		arg.Success,
		arg.ErrorMessage,
		arg.Metadata,
		arg.CreatedAt,
		arg.TorrentActivityID,
	)
	return err
}
