// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kept_torrents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkKeptTorrent = `-- name: CheckKeptTorrent :one
SELECT 1 FROM kept_torrents WHERE torrent_id = $1 LIMIT 1
`

func (q *Queries) CheckKeptTorrent(ctx context.Context, torrentID string) (int32, error) {
	row := q.db.QueryRow(ctx, checkKeptTorrent, torrentID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countKeptByUser = `-- name: CountKeptByUser :one
SELECT COUNT(*) FROM kept_torrents WHERE kept_by_id = $1
`

func (q *Queries) CountKeptByUser(ctx context.Context, keptByID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countKeptByUser, keptByID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countKeptExcluding = `-- name: CountKeptExcluding :one
SELECT COUNT(*) FROM kept_torrents WHERE kept_by_id = $1 AND torrent_id != $2
`

type CountKeptExcludingParams struct {
	KeptByID  int64  `json:"kept_by_id"`
	TorrentID string `json:"torrent_id"`
}

func (q *Queries) CountKeptExcluding(ctx context.Context, arg CountKeptExcludingParams) (int64, error) {
	row := q.db.QueryRow(ctx, countKeptExcluding, arg.KeptByID, arg.TorrentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteKeptTorrent = `-- name: DeleteKeptTorrent :exec
DELETE FROM kept_torrents WHERE torrent_id = $1 AND kept_by_id = $2
`

type DeleteKeptTorrentParams struct {
	TorrentID string `json:"torrent_id"`
	KeptByID  int64  `json:"kept_by_id"`
}

func (q *Queries) DeleteKeptTorrent(ctx context.Context, arg DeleteKeptTorrentParams) error {
	_, err := q.db.Exec(ctx, deleteKeptTorrent, arg.TorrentID, arg.KeptByID)
	return err
}

const deleteKeptTorrentAdmin = `-- name: DeleteKeptTorrentAdmin :exec
DELETE FROM kept_torrents WHERE torrent_id = $1
`

func (q *Queries) DeleteKeptTorrentAdmin(ctx context.Context, torrentID string) error {
	_, err := q.db.Exec(ctx, deleteKeptTorrentAdmin, torrentID)
	return err
}

const getAllKeptTorrentIDs = `-- name: GetAllKeptTorrentIDs :many
SELECT torrent_id FROM kept_torrents
`

func (q *Queries) GetAllKeptTorrentIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getAllKeptTorrentIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var torrent_id string
		if err := rows.Scan(&torrent_id); err != nil {
			return nil, err
		}
		items = append(items, torrent_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKeptTorrentByOwner = `-- name: GetKeptTorrentByOwner :one
SELECT id, torrent_id, filename, kept_by_id, kept_at FROM kept_torrents WHERE torrent_id = $1 AND kept_by_id = $2 LIMIT 1
`

type GetKeptTorrentByOwnerParams struct {
	TorrentID string `json:"torrent_id"`
	KeptByID  int64  `json:"kept_by_id"`
}

func (q *Queries) GetKeptTorrentByOwner(ctx context.Context, arg GetKeptTorrentByOwnerParams) (KeptTorrents, error) {
	row := q.db.QueryRow(ctx, getKeptTorrentByOwner, arg.TorrentID, arg.KeptByID)
	var i KeptTorrents
	err := row.Scan(
		&i.ID,
		&i.TorrentID,
		&i.Filename,
		&i.KeptByID,
		&i.KeptAt,
	)
	return i, err
}

const insertKeptTorrentAction = `-- name: InsertKeptTorrentAction :exec
INSERT INTO kept_torrent_actions (torrent_id, action, user_id, username, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertKeptTorrentActionParams struct {
	TorrentID string             `json:"torrent_id"`
	Action    string             `json:"action"`
	UserID    int64              `json:"user_id"`
	Username  *string            `json:"username"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertKeptTorrentAction(ctx context.Context, arg InsertKeptTorrentActionParams) error {
	_, err := q.db.Exec(ctx, insertKeptTorrentAction,
		arg.TorrentID,
		arg.Action,
		arg.UserID,
		arg.Username,
		arg.CreatedAt,
	)
	return err
}

const listKeptTorrents = `-- name: ListKeptTorrents :many
SELECT
    kt.id,
    kt.torrent_id,
    kt.filename,
    kt.kept_by_id,
    kt.kept_at,
    u.id          AS user_id_pk,
    u.user_id     AS user_user_id,
    u.username    AS user_username,
    u.first_name  AS user_first_name,
    u.last_name   AS user_last_name
FROM kept_torrents kt
JOIN users u ON u.id = kt.kept_by_id
ORDER BY kt.kept_at DESC
`

type ListKeptTorrentsRow struct {
	ID            int64              `json:"id"`
	TorrentID     string             `json:"torrent_id"`
	Filename      *string            `json:"filename"`
	KeptByID      int64              `json:"kept_by_id"`
	KeptAt        pgtype.Timestamptz `json:"kept_at"`
	UserIDPk      int64              `json:"user_id_pk"`
	UserUserID    int64              `json:"user_user_id"`
	UserUsername  *string            `json:"user_username"`
	UserFirstName *string            `json:"user_first_name"`
	UserLastName  *string            `json:"user_last_name"`
}

func (q *Queries) ListKeptTorrents(ctx context.Context) ([]ListKeptTorrentsRow, error) {
	rows, err := q.db.Query(ctx, listKeptTorrents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKeptTorrentsRow
	for rows.Next() {
		var i ListKeptTorrentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TorrentID,
			&i.Filename,
			&i.KeptByID,
			&i.KeptAt,
			&i.UserIDPk,
			&i.UserUserID,
			&i.UserUsername,
			&i.UserFirstName,
			&i.UserLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertKeptTorrent = `-- name: UpsertKeptTorrent :exec
INSERT INTO kept_torrents (torrent_id, filename, kept_by_id, kept_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (torrent_id, kept_by_id) DO UPDATE SET
    filename = EXCLUDED.filename,
    kept_at  = EXCLUDED.kept_at
`

type UpsertKeptTorrentParams struct {
	TorrentID string             `json:"torrent_id"`
	Filename  *string            `json:"filename"`
	KeptByID  int64              `json:"kept_by_id"`
	KeptAt    pgtype.Timestamptz `json:"kept_at"`
}

func (q *Queries) UpsertKeptTorrent(ctx context.Context, arg UpsertKeptTorrentParams) error {
	_, err := q.db.Exec(ctx, upsertKeptTorrent,
		arg.TorrentID,
		arg.Filename,
		arg.KeptByID,
		arg.KeptAt,
	)
	return err
}
