// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMessagesByUser = `-- name: CountMessagesByUser :one
SELECT COUNT(*) FROM messages WHERE user_id = $1
`

func (q *Queries) CountMessagesByUser(ctx context.Context, userID *int64) (int64, error) {
	row := q.db.QueryRow(ctx, countMessagesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMessagesByChat = `-- name: GetMessagesByChat :many
SELECT id, message_id, chat_id, user_id, thread_id, text, message_type, reply_to_id, is_forward, sent_at FROM messages WHERE chat_id = $1 ORDER BY sent_at DESC LIMIT $2
`

type GetMessagesByChatParams struct {
	ChatID int64 `json:"chat_id"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) GetMessagesByChat(ctx context.Context, arg GetMessagesByChatParams) ([]Messages, error) {
	rows, err := q.db.Query(ctx, getMessagesByChat, arg.ChatID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Messages
	for rows.Next() {
		var i Messages
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.ChatID,
			&i.UserID,
			&i.ThreadID,
			&i.Text,
			&i.MessageType,
			&i.ReplyToID,
			&i.IsForward,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesByUser = `-- name: GetMessagesByUser :many
SELECT id, message_id, chat_id, user_id, thread_id, text, message_type, reply_to_id, is_forward, sent_at FROM messages WHERE user_id = $1 ORDER BY sent_at DESC LIMIT $2
`

type GetMessagesByUserParams struct {
	UserID *int64 `json:"user_id"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) GetMessagesByUser(ctx context.Context, arg GetMessagesByUserParams) ([]Messages, error) {
	rows, err := q.db.Query(ctx, getMessagesByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Messages
	for rows.Next() {
		var i Messages
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.ChatID,
			&i.UserID,
			&i.ThreadID,
			&i.Text,
			&i.MessageType,
			&i.ReplyToID,
			&i.IsForward,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMessage = `-- name: UpsertMessage :one
INSERT INTO messages (message_id, chat_id, user_id, thread_id, text, message_type, reply_to_id, is_forward, sent_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (message_id, chat_id) DO UPDATE SET
    text         = EXCLUDED.text,
    message_type = EXCLUDED.message_type
RETURNING id, message_id, chat_id, user_id, thread_id, text, message_type, reply_to_id, is_forward, sent_at
`

type UpsertMessageParams struct {
	MessageID   int64              `json:"message_id"`
	ChatID      int64              `json:"chat_id"`
	UserID      *int64             `json:"user_id"`
	ThreadID    *int64             `json:"thread_id"`
	Text        *string            `json:"text"`
	MessageType string             `json:"message_type"`
	ReplyToID   *int64             `json:"reply_to_id"`
	IsForward   bool               `json:"is_forward"`
	SentAt      pgtype.Timestamptz `json:"sent_at"`
}

func (q *Queries) UpsertMessage(ctx context.Context, arg UpsertMessageParams) (Messages, error) {
	row := q.db.QueryRow(ctx, upsertMessage,
		arg.MessageID,
		arg.ChatID,
		arg.UserID,
		arg.ThreadID,
		arg.Text,
		arg.MessageType,
		arg.ReplyToID,
		arg.IsForward,
		arg.SentAt,
	)
	var i Messages
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.ChatID,
		&i.UserID,
		&i.ThreadID,
		&i.Text,
		&i.MessageType,
		&i.ReplyToID,
		&i.IsForward,
		&i.SentAt,
	)
	return i, err
}
