// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityLogs struct {
	ID              int64              `json:"id"`
	RequestID       *string            `json:"request_id"`
	UserID          int64              `json:"user_id"`
	ChatID          int64              `json:"chat_id"`
	Username        *string            `json:"username"`
	ActivityType    string             `json:"activity_type"`
	Command         *string            `json:"command"`
	MessageThreadID *int64             `json:"message_thread_id"`
	Success         bool               `json:"success"`
	ErrorMessage    *string            `json:"error_message"`
	Metadata        *json.RawMessage   `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Chats struct {
	ID        int64              `json:"id"`
	ChatID    int64              `json:"chat_id"`
	Title     *string            `json:"title"`
	Type      *string            `json:"type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type CommandLogs struct {
	ID              int64              `json:"id"`
	UserID          int64              `json:"user_id"`
	ChatID          int64              `json:"chat_id"`
	Username        *string            `json:"username"`
	Command         string             `json:"command"`
	FullCommand     *string            `json:"full_command"`
	MessageThreadID *int64             `json:"message_thread_id"`
	ExecutionTime   *int64             `json:"execution_time"`
	Success         bool               `json:"success"`
	ErrorMessage    *string            `json:"error_message"`
	ResponseLength  *int64             `json:"response_length"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type DownloadActivities struct {
	ID                int64              `json:"id"`
	RequestID         *string            `json:"request_id"`
	UserID            int64              `json:"user_id"`
	ChatID            int64              `json:"chat_id"`
	DownloadID        *string            `json:"download_id"`
	OriginalLink      *string            `json:"original_link"`
	FileName          *string            `json:"file_name"`
	FileSize          *int64             `json:"file_size"`
	Host              *string            `json:"host"`
	Action            string             `json:"action"`
	Success           bool               `json:"success"`
	ErrorMessage      *string            `json:"error_message"`
	Metadata          *json.RawMessage   `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	TorrentActivityID *int64             `json:"torrent_activity_id"`
}

type KeptTorrentActions struct {
	ID        int64              `json:"id"`
	TorrentID string             `json:"torrent_id"`
	Action    string             `json:"action"`
	UserID    int64              `json:"user_id"`
	Username  *string            `json:"username"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type KeptTorrents struct {
	ID        int64              `json:"id"`
	TorrentID string             `json:"torrent_id"`
	Filename  *string            `json:"filename"`
	KeptByID  int64              `json:"kept_by_id"`
	KeptAt    pgtype.Timestamptz `json:"kept_at"`
}

type SettingAudits struct {
	ID        int64              `json:"id"`
	Key       string             `json:"key"`
	OldValue  *string            `json:"old_value"`
	NewValue  *string            `json:"new_value"`
	ChangedBy int64              `json:"changed_by"`
	ChatID    *int64             `json:"chat_id"`
	ChangedAt pgtype.Timestamptz `json:"changed_at"`
}

type Settings struct {
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TorrentActivities struct {
	ID            int64              `json:"id"`
	RequestID     *string            `json:"request_id"`
	UserID        int64              `json:"user_id"`
	ChatID        int64              `json:"chat_id"`
	TorrentID     string             `json:"torrent_id"`
	TorrentHash   *string            `json:"torrent_hash"`
	TorrentName   *string            `json:"torrent_name"`
	MagnetLink    *string            `json:"magnet_link"`
	Action        string             `json:"action"`
	Status        *string            `json:"status"`
	FileSize      *int64             `json:"file_size"`
	Progress      pgtype.Numeric     `json:"progress"`
	Success       bool               `json:"success"`
	ErrorMessage  *string            `json:"error_message"`
	Metadata      json.RawMessage    `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	SelectedFiles json.RawMessage    `json:"selected_files"`
}

type Users struct {
	ID            int64              `json:"id"`
	UserID        int64              `json:"user_id"`
	Username      *string            `json:"username"`
	FirstName     *string            `json:"first_name"`
	LastName      *string            `json:"last_name"`
	IsSuperAdmin  bool               `json:"is_super_admin"`
	IsAllowed     bool               `json:"is_allowed"`
	FirstSeenAt   pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt    pgtype.Timestamptz `json:"last_seen_at"`
	TotalCommands int64              `json:"total_commands"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}
