// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSetting = `-- name: GetSetting :one
SELECT key, value, updated_at FROM settings WHERE key = $1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (Settings, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var i Settings
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}

const getSettingHistory = `-- name: GetSettingHistory :many
SELECT id, key, old_value, new_value, changed_by, chat_id, changed_at FROM setting_audits WHERE key = $1 ORDER BY changed_at DESC LIMIT $2
`

type GetSettingHistoryParams struct {
	Key   string `json:"key"`
	Limit int32  `json:"limit"`
}

func (q *Queries) GetSettingHistory(ctx context.Context, arg GetSettingHistoryParams) ([]SettingAudits, error) {
	rows, err := q.db.Query(ctx, getSettingHistory, arg.Key, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SettingAudits
	for rows.Next() {
		var i SettingAudits
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.OldValue,
			&i.NewValue,
			&i.ChangedBy,
			&i.ChatID,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSettingAudit = `-- name: InsertSettingAudit :exec
INSERT INTO setting_audits (key, old_value, new_value, changed_by, chat_id, changed_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertSettingAuditParams struct {
	Key       string             `json:"key"`
	OldValue  *string            `json:"old_value"`
	NewValue  *string            `json:"new_value"`
	ChangedBy int64              `json:"changed_by"`
	ChatID    *int64             `json:"chat_id"`
	ChangedAt pgtype.Timestamptz `json:"changed_at"`
}

func (q *Queries) InsertSettingAudit(ctx context.Context, arg InsertSettingAuditParams) error {
	_, err := q.db.Exec(ctx, insertSettingAudit,
		arg.Key,
		arg.OldValue,
		arg.NewValue,
		arg.ChangedBy,
		arg.ChatID,
		arg.ChangedAt,
	)
	return err
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO settings (key, value, updated_at)
VALUES ($1, $2, $3)
ON CONFLICT (key) DO UPDATE SET
    value      = EXCLUDED.value,
    updated_at = EXCLUDED.updated_at
`

type UpsertSettingParams struct {
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.Exec(ctx, upsertSetting, arg.Key, arg.Value, arg.UpdatedAt)
	return err
}
