// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActivityHeatmap = `-- name: GetActivityHeatmap :many

SELECT
    EXTRACT(DOW  FROM created_at)  AS day_of_week,
    EXTRACT(HOUR FROM created_at)  AS hour_of_day,
    COUNT(*)                       AS count
FROM command_logs
WHERE created_date BETWEEN $1 AND $2
GROUP BY day_of_week, hour_of_day
ORDER BY day_of_week, hour_of_day
`

type GetActivityHeatmapParams struct {
	CreatedDate   pgtype.Date `json:"created_date"`
	CreatedDate_2 pgtype.Date `json:"created_date_2"`
}

type GetActivityHeatmapRow struct {
	DayOfWeek float64 `json:"day_of_week"`
	HourOfDay float64 `json:"hour_of_day"`
	Count     int64   `json:"count"`
}

// ── activity heatmap (hour-of-day × day-of-week) ──────────────────────────
func (q *Queries) GetActivityHeatmap(ctx context.Context, arg GetActivityHeatmapParams) ([]GetActivityHeatmapRow, error) {
	rows, err := q.db.Query(ctx, getActivityHeatmap, arg.CreatedDate, arg.CreatedDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActivityHeatmapRow
	for rows.Next() {
		var i GetActivityHeatmapRow
		if err := rows.Scan(&i.DayOfWeek, &i.HourOfDay, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommandPopularity = `-- name: GetCommandPopularity :many

SELECT command, COUNT(*) AS total, SUM(CASE WHEN success THEN 1 ELSE 0 END) AS success_count
FROM command_logs
WHERE created_date BETWEEN $1 AND $2
GROUP BY command
ORDER BY total DESC
LIMIT $3
`

type GetCommandPopularityParams struct {
	CreatedDate   pgtype.Date `json:"created_date"`
	CreatedDate_2 pgtype.Date `json:"created_date_2"`
	Limit         int32       `json:"limit"`
}

type GetCommandPopularityRow struct {
	Command      string `json:"command"`
	Total        int64  `json:"total"`
	SuccessCount int64  `json:"success_count"`
}

// ── command popularity ─────────────────────────────────────────────────────
func (q *Queries) GetCommandPopularity(ctx context.Context, arg GetCommandPopularityParams) ([]GetCommandPopularityRow, error) {
	rows, err := q.db.Query(ctx, getCommandPopularity, arg.CreatedDate, arg.CreatedDate_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommandPopularityRow
	for rows.Next() {
		var i GetCommandPopularityRow
		if err := rows.Scan(&i.Command, &i.Total, &i.SuccessCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommandPopularityAllTime = `-- name: GetCommandPopularityAllTime :many
SELECT command, COUNT(*) AS total, SUM(CASE WHEN success THEN 1 ELSE 0 END) AS success_count
FROM command_logs
GROUP BY command
ORDER BY total DESC
LIMIT $1
`

type GetCommandPopularityAllTimeRow struct {
	Command      string `json:"command"`
	Total        int64  `json:"total"`
	SuccessCount int64  `json:"success_count"`
}

func (q *Queries) GetCommandPopularityAllTime(ctx context.Context, limit int32) ([]GetCommandPopularityAllTimeRow, error) {
	rows, err := q.db.Query(ctx, getCommandPopularityAllTime, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommandPopularityAllTimeRow
	for rows.Next() {
		var i GetCommandPopularityAllTimeRow
		if err := rows.Scan(&i.Command, &i.Total, &i.SuccessCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyStats = `-- name: GetDailyStats :many
SELECT stat_date, commands_total, commands_success, commands_fail, torrents_added, downloads_total, active_users, updated_at FROM daily_stats
WHERE stat_date BETWEEN $1 AND $2
ORDER BY stat_date ASC
`

type GetDailyStatsParams struct {
	StatDate   pgtype.Date `json:"stat_date"`
	StatDate_2 pgtype.Date `json:"stat_date_2"`
}

func (q *Queries) GetDailyStats(ctx context.Context, arg GetDailyStatsParams) ([]DailyStats, error) {
	rows, err := q.db.Query(ctx, getDailyStats, arg.StatDate, arg.StatDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyStats
	for rows.Next() {
		var i DailyStats
		if err := rows.Scan(
			&i.StatDate,
			&i.CommandsTotal,
			&i.CommandsSuccess,
			&i.CommandsFail,
			&i.TorrentsAdded,
			&i.DownloadsTotal,
			&i.ActiveUsers,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyStatsSingle = `-- name: GetDailyStatsSingle :one
SELECT stat_date, commands_total, commands_success, commands_fail, torrents_added, downloads_total, active_users, updated_at FROM daily_stats WHERE stat_date = $1
`

func (q *Queries) GetDailyStatsSingle(ctx context.Context, statDate pgtype.Date) (DailyStats, error) {
	row := q.db.QueryRow(ctx, getDailyStatsSingle, statDate)
	var i DailyStats
	err := row.Scan(
		&i.StatDate,
		&i.CommandsTotal,
		&i.CommandsSuccess,
		&i.CommandsFail,
		&i.TorrentsAdded,
		&i.DownloadsTotal,
		&i.ActiveUsers,
		&i.UpdatedAt,
	)
	return i, err
}

const getGlobalSummaryStats = `-- name: GetGlobalSummaryStats :one

SELECT
    (SELECT COUNT(*) FROM users  WHERE deleted_at IS NULL)                          AS total_users,
    (SELECT COUNT(*) FROM users  WHERE deleted_at IS NULL AND is_allowed = true)    AS allowed_users,
    (SELECT COUNT(*) FROM users  WHERE deleted_at IS NULL AND ban_reason IS NOT NULL) AS banned_users,
    (SELECT COUNT(*) FROM chats)                                                    AS total_chats,
    (SELECT COALESCE(SUM(total_commands),       0) FROM users WHERE deleted_at IS NULL) AS total_commands,
    (SELECT COALESCE(SUM(total_torrents_added), 0) FROM users WHERE deleted_at IS NULL) AS total_torrents,
    (SELECT COALESCE(SUM(total_downloads),      0) FROM users WHERE deleted_at IS NULL) AS total_downloads
`

type GetGlobalSummaryStatsRow struct {
	TotalUsers     int64       `json:"total_users"`
	AllowedUsers   int64       `json:"allowed_users"`
	BannedUsers    int64       `json:"banned_users"`
	TotalChats     int64       `json:"total_chats"`
	TotalCommands  interface{} `json:"total_commands"`
	TotalTorrents  interface{} `json:"total_torrents"`
	TotalDownloads interface{} `json:"total_downloads"`
}

// ── summary stats ──────────────────────────────────────────────────────────
func (q *Queries) GetGlobalSummaryStats(ctx context.Context) (GetGlobalSummaryStatsRow, error) {
	row := q.db.QueryRow(ctx, getGlobalSummaryStats)
	var i GetGlobalSummaryStatsRow
	err := row.Scan(
		&i.TotalUsers,
		&i.AllowedUsers,
		&i.BannedUsers,
		&i.TotalChats,
		&i.TotalCommands,
		&i.TotalTorrents,
		&i.TotalDownloads,
	)
	return i, err
}

const getTopUsersByCommands = `-- name: GetTopUsersByCommands :many

SELECT u.user_id, u.username, u.first_name, u.last_name, u.total_commands
FROM users u
WHERE u.deleted_at IS NULL
ORDER BY u.total_commands DESC
LIMIT $1
`

type GetTopUsersByCommandsRow struct {
	UserID        int64   `json:"user_id"`
	Username      *string `json:"username"`
	FirstName     *string `json:"first_name"`
	LastName      *string `json:"last_name"`
	TotalCommands int64   `json:"total_commands"`
}

// ── top users ──────────────────────────────────────────────────────────────
func (q *Queries) GetTopUsersByCommands(ctx context.Context, limit int32) ([]GetTopUsersByCommandsRow, error) {
	rows, err := q.db.Query(ctx, getTopUsersByCommands, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopUsersByCommandsRow
	for rows.Next() {
		var i GetTopUsersByCommandsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.TotalCommands,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopUsersByCommandsInRange = `-- name: GetTopUsersByCommandsInRange :many
SELECT uds.user_id, u.username, u.first_name, u.last_name,
       SUM(uds.commands) AS commands
FROM user_daily_stats uds
JOIN users u ON u.id = uds.user_id
WHERE uds.stat_date BETWEEN $1 AND $2
  AND u.deleted_at IS NULL
GROUP BY uds.user_id, u.username, u.first_name, u.last_name
ORDER BY commands DESC
LIMIT $3
`

type GetTopUsersByCommandsInRangeParams struct {
	StatDate   pgtype.Date `json:"stat_date"`
	StatDate_2 pgtype.Date `json:"stat_date_2"`
	Limit      int32       `json:"limit"`
}

type GetTopUsersByCommandsInRangeRow struct {
	UserID    int64   `json:"user_id"`
	Username  *string `json:"username"`
	FirstName *string `json:"first_name"`
	LastName  *string `json:"last_name"`
	Commands  int64   `json:"commands"`
}

func (q *Queries) GetTopUsersByCommandsInRange(ctx context.Context, arg GetTopUsersByCommandsInRangeParams) ([]GetTopUsersByCommandsInRangeRow, error) {
	rows, err := q.db.Query(ctx, getTopUsersByCommandsInRange, arg.StatDate, arg.StatDate_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopUsersByCommandsInRangeRow
	for rows.Next() {
		var i GetTopUsersByCommandsInRangeRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Commands,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopUsersByDownloads = `-- name: GetTopUsersByDownloads :many
SELECT u.user_id, u.username, u.first_name, u.last_name, u.total_downloads
FROM users u
WHERE u.deleted_at IS NULL
ORDER BY u.total_downloads DESC
LIMIT $1
`

type GetTopUsersByDownloadsRow struct {
	UserID         int64   `json:"user_id"`
	Username       *string `json:"username"`
	FirstName      *string `json:"first_name"`
	LastName       *string `json:"last_name"`
	TotalDownloads int64   `json:"total_downloads"`
}

func (q *Queries) GetTopUsersByDownloads(ctx context.Context, limit int32) ([]GetTopUsersByDownloadsRow, error) {
	rows, err := q.db.Query(ctx, getTopUsersByDownloads, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopUsersByDownloadsRow
	for rows.Next() {
		var i GetTopUsersByDownloadsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.TotalDownloads,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopUsersByTorrents = `-- name: GetTopUsersByTorrents :many
SELECT u.user_id, u.username, u.first_name, u.last_name, u.total_torrents_added
FROM users u
WHERE u.deleted_at IS NULL
ORDER BY u.total_torrents_added DESC
LIMIT $1
`

type GetTopUsersByTorrentsRow struct {
	UserID             int64   `json:"user_id"`
	Username           *string `json:"username"`
	FirstName          *string `json:"first_name"`
	LastName           *string `json:"last_name"`
	TotalTorrentsAdded int64   `json:"total_torrents_added"`
}

func (q *Queries) GetTopUsersByTorrents(ctx context.Context, limit int32) ([]GetTopUsersByTorrentsRow, error) {
	rows, err := q.db.Query(ctx, getTopUsersByTorrents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopUsersByTorrentsRow
	for rows.Next() {
		var i GetTopUsersByTorrentsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.TotalTorrentsAdded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserDailyStats = `-- name: GetUserDailyStats :many
SELECT id, stat_date, user_id, commands, torrents_added, downloads FROM user_daily_stats
WHERE user_id = $1 AND stat_date BETWEEN $2 AND $3
ORDER BY stat_date ASC
`

type GetUserDailyStatsParams struct {
	UserID     int64       `json:"user_id"`
	StatDate   pgtype.Date `json:"stat_date"`
	StatDate_2 pgtype.Date `json:"stat_date_2"`
}

func (q *Queries) GetUserDailyStats(ctx context.Context, arg GetUserDailyStatsParams) ([]UserDailyStats, error) {
	rows, err := q.db.Query(ctx, getUserDailyStats, arg.UserID, arg.StatDate, arg.StatDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserDailyStats
	for rows.Next() {
		var i UserDailyStats
		if err := rows.Scan(
			&i.ID,
			&i.StatDate,
			&i.UserID,
			&i.Commands,
			&i.TorrentsAdded,
			&i.Downloads,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementDailyCommand = `-- name: IncrementDailyCommand :exec

INSERT INTO daily_stats (stat_date, commands_total, commands_success, commands_fail, updated_at)
VALUES ($1, 1, CASE WHEN $2::bool THEN 1 ELSE 0 END, CASE WHEN $2::bool THEN 0 ELSE 1 END, now())
ON CONFLICT (stat_date) DO UPDATE SET
    commands_total   = daily_stats.commands_total   + 1,
    commands_success = daily_stats.commands_success + CASE WHEN $2::bool THEN 1 ELSE 0 END,
    commands_fail    = daily_stats.commands_fail    + CASE WHEN $2::bool THEN 0 ELSE 1 END,
    updated_at       = now()
`

type IncrementDailyCommandParams struct {
	StatDate pgtype.Date `json:"stat_date"`
	Column2  bool        `json:"column_2"`
}

// ── daily_stats ────────────────────────────────────────────────────────────
func (q *Queries) IncrementDailyCommand(ctx context.Context, arg IncrementDailyCommandParams) error {
	_, err := q.db.Exec(ctx, incrementDailyCommand, arg.StatDate, arg.Column2)
	return err
}

const incrementDailyDownload = `-- name: IncrementDailyDownload :exec
INSERT INTO daily_stats (stat_date, downloads_total, updated_at)
VALUES ($1, 1, now())
ON CONFLICT (stat_date) DO UPDATE SET
    downloads_total = daily_stats.downloads_total + 1,
    updated_at      = now()
`

func (q *Queries) IncrementDailyDownload(ctx context.Context, statDate pgtype.Date) error {
	_, err := q.db.Exec(ctx, incrementDailyDownload, statDate)
	return err
}

const incrementDailyTorrent = `-- name: IncrementDailyTorrent :exec
INSERT INTO daily_stats (stat_date, torrents_added, updated_at)
VALUES ($1, 1, now())
ON CONFLICT (stat_date) DO UPDATE SET
    torrents_added = daily_stats.torrents_added + 1,
    updated_at     = now()
`

func (q *Queries) IncrementDailyTorrent(ctx context.Context, statDate pgtype.Date) error {
	_, err := q.db.Exec(ctx, incrementDailyTorrent, statDate)
	return err
}

const incrementUserDailyCommand = `-- name: IncrementUserDailyCommand :exec

INSERT INTO user_daily_stats (stat_date, user_id, commands)
VALUES ($1, $2, 1)
ON CONFLICT (stat_date, user_id) DO UPDATE SET
    commands = user_daily_stats.commands + 1
`

type IncrementUserDailyCommandParams struct {
	StatDate pgtype.Date `json:"stat_date"`
	UserID   int64       `json:"user_id"`
}

// ── user_daily_stats ───────────────────────────────────────────────────────
func (q *Queries) IncrementUserDailyCommand(ctx context.Context, arg IncrementUserDailyCommandParams) error {
	_, err := q.db.Exec(ctx, incrementUserDailyCommand, arg.StatDate, arg.UserID)
	return err
}

const incrementUserDailyDownload = `-- name: IncrementUserDailyDownload :exec
INSERT INTO user_daily_stats (stat_date, user_id, downloads)
VALUES ($1, $2, 1)
ON CONFLICT (stat_date, user_id) DO UPDATE SET
    downloads = user_daily_stats.downloads + 1
`

type IncrementUserDailyDownloadParams struct {
	StatDate pgtype.Date `json:"stat_date"`
	UserID   int64       `json:"user_id"`
}

func (q *Queries) IncrementUserDailyDownload(ctx context.Context, arg IncrementUserDailyDownloadParams) error {
	_, err := q.db.Exec(ctx, incrementUserDailyDownload, arg.StatDate, arg.UserID)
	return err
}

const incrementUserDailyTorrent = `-- name: IncrementUserDailyTorrent :exec
INSERT INTO user_daily_stats (stat_date, user_id, torrents_added)
VALUES ($1, $2, 1)
ON CONFLICT (stat_date, user_id) DO UPDATE SET
    torrents_added = user_daily_stats.torrents_added + 1
`

type IncrementUserDailyTorrentParams struct {
	StatDate pgtype.Date `json:"stat_date"`
	UserID   int64       `json:"user_id"`
}

func (q *Queries) IncrementUserDailyTorrent(ctx context.Context, arg IncrementUserDailyTorrentParams) error {
	_, err := q.db.Exec(ctx, incrementUserDailyTorrent, arg.StatDate, arg.UserID)
	return err
}
