// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: torrent_activities.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTorrentAddsByUser = `-- name: CountTorrentAddsByUser :one
SELECT COUNT(*) FROM torrent_activities WHERE user_id = $1 AND action = 'add'
`

func (q *Queries) CountTorrentAddsByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countTorrentAddsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTorrentActivities = `-- name: GetTorrentActivities :many
SELECT id, request_id, user_id, chat_id, torrent_id, torrent_hash, torrent_name, magnet_link, action, status, file_size, progress, success, error_message, metadata, created_at, selected_files FROM torrent_activities
WHERE ($1::bigint IS NULL OR user_id = $1)
ORDER BY created_at DESC
LIMIT $2
`

type GetTorrentActivitiesParams struct {
	Column1 int64 `json:"column_1"`
	Limit   int32 `json:"limit"`
}

func (q *Queries) GetTorrentActivities(ctx context.Context, arg GetTorrentActivitiesParams) ([]TorrentActivities, error) {
	rows, err := q.db.Query(ctx, getTorrentActivities, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TorrentActivities
	for rows.Next() {
		var i TorrentActivities
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.UserID,
			&i.ChatID,
			&i.TorrentID,
			&i.TorrentHash,
			&i.TorrentName,
			&i.MagnetLink,
			&i.Action,
			&i.Status,
			&i.FileSize,
			&i.Progress,
			&i.Success,
			&i.ErrorMessage,
			&i.Metadata,
			&i.CreatedAt,
			&i.SelectedFiles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTorrentActivity = `-- name: InsertTorrentActivity :exec
INSERT INTO torrent_activities (
    request_id, user_id, chat_id, torrent_id, torrent_hash, torrent_name,
    magnet_link, action, status, file_size, progress, success, error_message,
    metadata, created_at, selected_files
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12, $13,
    $14, $15, $16
)
`

type InsertTorrentActivityParams struct {
	RequestID     *string            `json:"request_id"`
	UserID        int64              `json:"user_id"`
	ChatID        int64              `json:"chat_id"`
	TorrentID     string             `json:"torrent_id"`
	TorrentHash   *string            `json:"torrent_hash"`
	TorrentName   *string            `json:"torrent_name"`
	MagnetLink    *string            `json:"magnet_link"`
	Action        string             `json:"action"`
	Status        *string            `json:"status"`
	FileSize      *int64             `json:"file_size"`
	Progress      pgtype.Numeric     `json:"progress"`
	Success       bool               `json:"success"`
	ErrorMessage  *string            `json:"error_message"`
	Metadata      json.RawMessage    `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	SelectedFiles json.RawMessage    `json:"selected_files"`
}

func (q *Queries) InsertTorrentActivity(ctx context.Context, arg InsertTorrentActivityParams) error {
	_, err := q.db.Exec(ctx, insertTorrentActivity,
		arg.RequestID,
		arg.UserID,
		arg.ChatID,
		arg.TorrentID,
		arg.TorrentHash,
		arg.TorrentName,
		arg.MagnetLink,
		arg.Action,
		arg.Status,
		arg.FileSize,
		arg.Progress,
		arg.Success,
		arg.ErrorMessage,
		arg.Metadata,
		arg.CreatedAt,
		arg.SelectedFiles,
	)
	return err
}
