// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, user_id, username, first_name, last_name, is_super_admin, is_allowed, first_seen_at, last_seen_at, total_commands, created_at, updated_at, deleted_at FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (Users, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.IsSuperAdmin,
		&i.IsAllowed,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.TotalCommands,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByUserID = `-- name: GetUserByUserID :one
SELECT id, user_id, username, first_name, last_name, is_super_admin, is_allowed, first_seen_at, last_seen_at, total_commands, created_at, updated_at, deleted_at FROM users WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByUserID(ctx context.Context, userID int64) (Users, error) {
	row := q.db.QueryRow(ctx, getUserByUserID, userID)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.IsSuperAdmin,
		&i.IsAllowed,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.TotalCommands,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const incrementUserCommands = `-- name: IncrementUserCommands :exec
UPDATE users SET total_commands = total_commands + 1 WHERE id = $1
`

func (q *Queries) IncrementUserCommands(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementUserCommands, id)
	return err
}

const lockUserForUpdate = `-- name: LockUserForUpdate :one
SELECT id, user_id, username, first_name, last_name, is_super_admin, is_allowed, first_seen_at, last_seen_at, total_commands, created_at, updated_at, deleted_at FROM users WHERE user_id = $1 AND deleted_at IS NULL FOR UPDATE
`

func (q *Queries) LockUserForUpdate(ctx context.Context, userID int64) (Users, error) {
	row := q.db.QueryRow(ctx, lockUserForUpdate, userID)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.IsSuperAdmin,
		&i.IsAllowed,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.TotalCommands,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (
    user_id, username, first_name, last_name, is_super_admin, is_allowed,
    first_seen_at, last_seen_at, total_commands, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, false,
    $6, $7, 0, $8, $9
)
ON CONFLICT (user_id) DO UPDATE SET
    username       = EXCLUDED.username,
    first_name     = EXCLUDED.first_name,
    last_name      = EXCLUDED.last_name,
    is_super_admin = EXCLUDED.is_super_admin,
    last_seen_at   = EXCLUDED.last_seen_at,
    updated_at     = EXCLUDED.updated_at
RETURNING id, user_id, username, first_name, last_name, is_super_admin, is_allowed, first_seen_at, last_seen_at, total_commands, created_at, updated_at, deleted_at
`

type UpsertUserParams struct {
	UserID       int64              `json:"user_id"`
	Username     *string            `json:"username"`
	FirstName    *string            `json:"first_name"`
	LastName     *string            `json:"last_name"`
	IsSuperAdmin bool               `json:"is_super_admin"`
	FirstSeenAt  pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt   pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (Users, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.UserID,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.IsSuperAdmin,
		arg.FirstSeenAt,
		arg.LastSeenAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.IsSuperAdmin,
		&i.IsAllowed,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.TotalCommands,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
