// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_chat_memberships.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMembership = `-- name: GetMembership :one
SELECT id, user_id, chat_id, first_seen_at, last_seen_at, command_count FROM user_chat_memberships WHERE user_id = $1 AND chat_id = $2
`

type GetMembershipParams struct {
	UserID int64 `json:"user_id"`
	ChatID int64 `json:"chat_id"`
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (UserChatMemberships, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.UserID, arg.ChatID)
	var i UserChatMemberships
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChatID,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CommandCount,
	)
	return i, err
}

const getMembershipsByChat = `-- name: GetMembershipsByChat :many
SELECT id, user_id, chat_id, first_seen_at, last_seen_at, command_count FROM user_chat_memberships WHERE chat_id = $1 ORDER BY last_seen_at DESC
`

func (q *Queries) GetMembershipsByChat(ctx context.Context, chatID int64) ([]UserChatMemberships, error) {
	rows, err := q.db.Query(ctx, getMembershipsByChat, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserChatMemberships
	for rows.Next() {
		var i UserChatMemberships
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ChatID,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.CommandCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMembershipsByUser = `-- name: GetMembershipsByUser :many
SELECT id, user_id, chat_id, first_seen_at, last_seen_at, command_count FROM user_chat_memberships WHERE user_id = $1 ORDER BY last_seen_at DESC
`

func (q *Queries) GetMembershipsByUser(ctx context.Context, userID int64) ([]UserChatMemberships, error) {
	rows, err := q.db.Query(ctx, getMembershipsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserChatMemberships
	for rows.Next() {
		var i UserChatMemberships
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ChatID,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.CommandCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementMembershipCommandCount = `-- name: IncrementMembershipCommandCount :exec
UPDATE user_chat_memberships
SET command_count = command_count + 1, last_seen_at = $3
WHERE user_id = $1 AND chat_id = $2
`

type IncrementMembershipCommandCountParams struct {
	UserID     int64              `json:"user_id"`
	ChatID     int64              `json:"chat_id"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
}

func (q *Queries) IncrementMembershipCommandCount(ctx context.Context, arg IncrementMembershipCommandCountParams) error {
	_, err := q.db.Exec(ctx, incrementMembershipCommandCount, arg.UserID, arg.ChatID, arg.LastSeenAt)
	return err
}

const upsertUserChatMembership = `-- name: UpsertUserChatMembership :exec
INSERT INTO user_chat_memberships (user_id, chat_id, first_seen_at, last_seen_at, command_count)
VALUES ($1, $2, $3, $3, 0)
ON CONFLICT (user_id, chat_id) DO UPDATE SET
    last_seen_at = EXCLUDED.last_seen_at
`

type UpsertUserChatMembershipParams struct {
	UserID      int64              `json:"user_id"`
	ChatID      int64              `json:"chat_id"`
	FirstSeenAt pgtype.Timestamptz `json:"first_seen_at"`
}

func (q *Queries) UpsertUserChatMembership(ctx context.Context, arg UpsertUserChatMembershipParams) error {
	_, err := q.db.Exec(ctx, upsertUserChatMembership, arg.UserID, arg.ChatID, arg.FirstSeenAt)
	return err
}
